apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: large-e2-nodes
spec:
  priorities:
  - machineFamily: e2
    minCores: 32
  activeMigration:
    optimizeRulePriority: false
  nodePoolAutoCreation:
    enabled: true
