apiVersion: apps/v1
kind: Deployment
metadata:
  name: balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: balanced-pod
  template:
    metadata:
      labels:
        pod: balanced-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:1
        resources:
          requests:
            cpu: "4"
