apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2d-milan
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: timeserver-pod
  template:
    metadata:
      labels:
        pod: timeserver-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
        supported-cpu-platform.cloud.google.com/AMD_Milan: "true"
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:1
        resources:
          requests:
            cpu: "4"
