apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-out
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: scale-out-pod
  template:
    metadata:
      labels:
        pod: scale-out-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:1
        resources:
          requests:
            cpu: "4"
