apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2a
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: t2a-pod
  template:
    metadata:
      labels:
        pod: t2a-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
      - name: timeserver-container
        image: nginx
        resources:
          requests:
            cpu: "4"
