apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2d
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: t2d-pod
  template:
    metadata:
      labels:
        pod: t2d-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:1
        resources:
          requests:
            cpu: "4"
