apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: c3-pod
  template:
    metadata:
      labels:
        pod: c3-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Performance
        cloud.google.com/machine-family: c3
      containers:
      - name: pause-container
        image: "k8s.gcr.io/pause"

