apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-large
spec:
  replicas: 5
  selector:
    matchLabels:
      pod: timeserver-generic-pod
  template:
    metadata:
      labels:
        pod: timeserver-generic-pod
    spec:
      nodeSelector:
        cloud.google.com/compute-class: large-e2-nodes
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:1
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
